add_newline = true

[character] 
success_symbol = "ğŸ¬ "
error_symbol = "â˜ ï¸ "

[directory]
style = "bold cyan"

[package]
disabled = false

[nodejs]
symbol = "ğŸ™ "

[git_branch]
symbol = "ğŸŒ± "

[git_status]
style = "bold white"
conflicted = " ğŸ³"
ahead = " ğŸ’¨ "
behind =" ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤·â€ "
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green)'
renamed = " ğŸ‘… "
deleted = " ğŸ—‘ "
